--- Shared Alien Biomes prototype name lists used by craft-deco-2.
---@class AlienBiomesConstants
---@field trees string[]
---@field rock_colors string[]
---@field rock_bases string[]
---@field tree_remnants table<string, string>

local constants = {}

constants.trees = {
    "tree-wetland-a",
    "tree-wetland-b",
    "tree-wetland-c",
    "tree-wetland-d",
    "tree-wetland-e",
    "tree-wetland-f",
    "tree-wetland-g",
    "tree-wetland-h",
    "tree-wetland-i",
    "tree-wetland-j",
    "tree-wetland-k",
    "tree-wetland-l",
    "tree-wetland-m",
    "tree-wetland-n",
    "tree-wetland-o",
    "tree-grassland-a",
    "tree-grassland-b",
    "tree-grassland-c",
    "tree-grassland-d",
    "tree-grassland-e",
    "tree-grassland-f",
    "tree-grassland-g",
    "tree-grassland-h",
    "tree-grassland-h2",
    "tree-grassland-h3",
    "tree-grassland-i",
    "tree-grassland-j",
    "tree-grassland-k",
    "tree-grassland-l",
    "tree-grassland-m",
    "tree-grassland-n",
    "tree-grassland-o",
    "tree-grassland-p",
    "tree-grassland-q",
    "tree-dryland-a",
    "tree-dryland-b",
    "tree-dryland-c",
    "tree-dryland-d",
    "tree-dryland-e",
    "tree-dryland-f",
    "tree-dryland-g",
    "tree-dryland-h",
    "tree-dryland-i",
    "tree-dryland-j",
    "tree-dryland-k",
    "tree-dryland-l",
    "tree-dryland-m",
    "tree-dryland-n",
    "tree-dryland-o",
    "tree-desert-a",
    "tree-desert-b",
    "tree-desert-c",
    "tree-desert-d",
    "tree-desert-e",
    "tree-desert-f",
    "tree-desert-g",
    "tree-desert-h",
    "tree-desert-i",
    "tree-desert-j",
    "tree-desert-k",
    "tree-desert-l",
    "tree-desert-m",
    "tree-desert-n",
    "tree-snow-a",
    "tree-volcanic-a",
    "tree-palm-a",
    "tree-palm-b",
}

constants.rock_colors = {
    "tan",
    "white",
    "grey",
    "black",
    "purple",
    "red",
    "violet",
    "dustyrose",
    "cream",
    "brown",
    "beige",
    "aubergine",
}

constants.rock_bases = {
    "rock-huge",
    "rock-big",
}

constants.tree_remnants = {
    ["tree-wetland-a"] = "tree-oaktapus-stump",
    ["tree-wetland-b"] = "tree-specter-stump",
    ["tree-wetland-c"] = "tree-05-stump",
    ["tree-wetland-d"] = "tree-specter-stump",
    ["tree-wetland-e"] = "tree-04-stump",
    ["tree-wetland-f"] = "tree-mangrove-stump",
    ["tree-wetland-g"] = "tree-05-stump",
    ["tree-wetland-h"] = "tree-07-stump",
    ["tree-wetland-i"] = "tree-mangrove-stump",
    ["tree-wetland-j"] = "tree-ash-stump",
    ["tree-wetland-k"] = "tree-03-stump",
    ["tree-wetland-l"] = "tree-oaktapus-stump",
    ["tree-wetland-m"] = "tree-07-stump",
    ["tree-wetland-n"] = "tree-mangrove-stump",
    ["tree-wetland-o"] = "tree-01-stump",
    ["tree-grassland-a"] = "tree-ash-stump",
    ["tree-grassland-b"] = "tree-scarecrow-stump",
    ["tree-grassland-c"] = "tree-oaktapus-stump",
    ["tree-grassland-d"] = "tree-ash-stump",
    ["tree-grassland-e"] = "tree-scarecrow-stump",
    ["tree-grassland-f"] = "tree-ash-stump",
    ["tree-grassland-g"] = "tree-ash-stump",
    ["tree-grassland-h"] = "tree-05-stump",
    ["tree-grassland-h2"] = "tree-04-stump",
    ["tree-grassland-h3"] = "tree-scarecrow-stump",
    ["tree-grassland-i"] = "tree-greypine-stump",
    ["tree-grassland-j"] = "tree-08-stump",
    ["tree-grassland-k"] = "tree-02-stump",
    ["tree-grassland-l"] = "tree-specter-stump",
    ["tree-grassland-m"] = "tree-ash-stump",
    ["tree-grassland-n"] = "tree-greypine-stump",
    ["tree-grassland-o"] = "tree-02-stump",
    ["tree-grassland-p"] = "tree-05-stump",
    ["tree-grassland-q"] = "tree-specter-stump",
    ["tree-dryland-a"] = "tree-willow-stump",
    ["tree-dryland-b"] = "tree-04-stump",
    ["tree-dryland-c"] = "tree-scarecrow-stump",
    ["tree-dryland-d"] = "tree-04-stump",
    ["tree-dryland-e"] = "tree-oaktapus-stump",
    ["tree-dryland-f"] = "tree-08-stump",
    ["tree-dryland-g"] = "tree-oaktapus-stump",
    ["tree-dryland-h"] = "tree-04-stump",
    ["tree-dryland-i"] = "tree-willow-stump",
    ["tree-dryland-j"] = "tree-01-stump",
    ["tree-dryland-k"] = "tree-greypine-stump",
    ["tree-dryland-l"] = "tree-01-stump",
    ["tree-dryland-m"] = "tree-scarecrow-stump",
    ["tree-dryland-n"] = "tree-06-stump",
    ["tree-dryland-o"] = "tree-01-stump",
    ["tree-desert-a"] = "tree-08-stump",
    ["tree-desert-b"] = "tree-pear-stump",
    ["tree-desert-c"] = "tree-greypine-stump",
    ["tree-desert-d"] = "tree-pear-stump",
    ["tree-desert-e"] = "tree-08-stump",
    ["tree-desert-f"] = "tree-pear-stump",
    ["tree-desert-g"] = "tree-06-stump",
    ["tree-desert-h"] = "tree-baobab-stump",
    ["tree-desert-i"] = "tree-greypine-stump",
    ["tree-desert-j"] = "tree-09-stump",
    ["tree-desert-k"] = "tree-baobab-stump",
    ["tree-desert-l"] = "tree-09-stump",
    ["tree-desert-m"] = "tree-baobab-stump",
    ["tree-desert-n"] = "tree-09-stump",
    ["tree-snow-a"] = "tree-02-stump",
    ["tree-volcanic-a"] = "tree-02-stump",
    ["tree-palm-a"] = "tree-02-stump",
}

return constants